version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "8001:8001"
    environment:
      - DEBUG=false
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/medreserve
      - REDIS_URL=redis://redis:6379/0
      - SPRING_BOOT_BASE_URL=http://backend:8080/api
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-change-in-production}
      - CORS_ORIGINS=["http://localhost:3000","http://localhost:8080"]
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - medreserve-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - medreserve-network

volumes:
  redis_data:

networks:
  medreserve-network:
    driver: bridge
